version: '3'
services:
  php:
    image: php:8.3-apache
    container_name: meu-php-quiz
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./home/imply/php-imply/lista3/GL QUIZ:/var/www/html
    links: 
      - db

      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: desafio3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgres